version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: serverless-app
    tty: true
    stdin_open: true
    working_dir: /app
    ports:
      - 1323:1323
    volumes:
      - ./:/app
      - pkg:/go/pkg/mod
  serverless:
    image: node:18-bullseye
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  pkg:
  node_modules:
